#!/bin/bash

# Apps
brew install Caskroom/cask/sublime-text
brew install Caskroom/cask/iterm2
brew install Caskroom/cask/vlc
brew install Caskroom/cask/spotify

# Tools
brew install node
brew install git
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
